# Generated by Django 3.0.5 on 2024-06-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
