# Generated by Django 3.0.5 on 2024-06-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0004_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='banner_imgs/'),
        ),
    ]
