# Generated by Django 3.0.5 on 2024-06-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0007_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='count',
            options={'verbose_name_plural': '4. Counts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '6. ProductAttributes'},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
